name: nexus_ai
description: "Nexus AI - Smart Professional Identity Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  pdf: ^3.10.7
  printing: ^5.11.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.0.5
  file_picker: ^8.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.3.0
  http: ^1.1.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  media_link_generator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true